export const waterMonthlyDemandReportForm = [
    {
      key: "tenantId",
      type: "select",
      placeholderLabelKey: "Select ULB Name",
      gridSm: 4,
      className: "applicant-details-error autocomplete-dropdown",
      jsonPath: "reportForm.tenantId",
      sourceJsonPath: "applyScreenMdmsData.tenant.tenants",
      required: true,
      labelKey: "ULB Name",
      localePrefix: {
        moduleName: "TENANT",
        masterName: "TENANTS",
      },
      // onChange: onChangeTest,
    },
    {
      key: "fromDate",
      type: "date",
      jsonPath: "reportForm.fromDate",
      labelKey: "From Date",
      placeholderLabelKey: "Select Date",
      // localePrefix,
      gridSm: 4,
      // className,
      required: true,
      // isDisabled: false,
    },
    {
        key: "toDate",
        type: "date",
        jsonPath: "reportForm.toDate",
        // sourceJsonPath,
        labelKey: "To Date",
        placeholderLabelKey: "Select Date",
        // localePrefix,
        gridSm: 4,
        // className,
        required: true,
        // isDisabled: false,
    },
    {
        key: "connectionType",
        type: "select",
        placeholderLabelKey: "Select Connection Type",
        gridSm: 4,
        // className: "applicant-details-error autocomplete-dropdown",
        jsonPath: "reportForm.connectionType",
        sourceJsonPath: "reportDropdownOpts.connectionType",
        required: false,
        labelKey: "Connection Type",
        optionValue: "value",
        optionLabel: "code",
    },
    {
        key: "ward",
        type: "text",
        placeholderLabelKey: "Select Ward",
        gridSm: 4,
        // className: "applicant-details-error autocomplete-dropdown",
        jsonPath: "reportForm.ward",
        // sourceJsonPath: "applyScreenMdmsData.tenant.tenants",
        required: true,
        labelKey: "Ward (Eg NIL,01,02,..)",
      },
  ]